---
name: Checks and Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  java-checks-and-tests:
    name: Java Checks and Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Maven Checks
        run: make check

      - name: Run Tests
        run: make test
