---
name: Checks and Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  java-checks-and-tests:
    name: Java Checks and Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Maven Checks
        run: make check

      - name: Run Tests
        run: make test

      - name: Run Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # NB: fail_ci_if_error is enabled to make any teething issues with Codecov visible.
          # If Codecov has outage issues in the future, this can be toggled to false, to allow the action to pass.
          fail_ci_if_error: true
